# Generated by Django 4.2.5 on 2023-12-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('Presales/Assesment', 'Presales/Assesment'), ('Sales', 'Sales'), ('Documentation', 'Documentation'), ('Visa Team', 'Visa Team'), ('HR', 'HR'), ('Developement Team', 'Developement Team'), ('Design Team', 'Design Team'), ('Account Team', 'Account Team')], max_length=20, null=True),
        ),
    ]
