# Generated by Django 5.0 on 2023-12-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visacountry',
            old_name='Country',
            new_name='country',
        ),
    ]
