# Generated by Django 4.2.5 on 2023-12-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_alter_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='employee',
        ),
    ]
