# Generated by Django 4.2.5 on 2023-12-30 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_remove_faq_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.employee'),
        ),
    ]
