# Generated by Django 4.2.5 on 2023-12-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_faq_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='test',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
