# Generated by Django 4.2.5 on 2023-12-30 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_faq_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='test',
        ),
    ]
