# Generated by Django 4.2.5 on 2024-01-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0006_remove_faq_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
