# Generated by Django 5.0 on 2023-12-14 10:47

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0007_alter_visacountry_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visacountry',
            name='country',
            field=django_countries.fields.CountryField(max_length=746, multiple=True),
        ),
    ]
