# Generated by Django 4.2.5 on 2023-12-22 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0007_merge_20231222_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='adhar_card_back',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='adhar_card_front',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='pancard',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='registration_certificate',
        ),
        migrations.CreateModel(
            name='AgentKyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar_card_front', models.FileField(blank=True, null=True, upload_to='media/Agent/Kyc')),
                ('adhar_card_back', models.FileField(blank=True, null=True, upload_to='media/Agent/Kyc')),
                ('pancard', models.FileField(blank=True, null=True, upload_to='media/Agent/Kyc')),
                ('registration_certificate', models.FileField(blank=True, null=True, upload_to='media/Agent/Kyc')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.agent')),
            ],
        ),
    ]
