# Generated by Django 5.0 on 2023-12-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0008_alter_visacountry_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visacountry',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
