# Generated by Django 4.2.5 on 2023-12-22 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0008_remove_agent_adhar_card_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentkyc',
            name='outsourceagent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.outsourcingagent'),
        ),
    ]
