# Generated by Django 4.2.5 on 2023-12-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0009_agentkyc_outsourceagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentkyc',
            name='uploaded_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
