# Generated by Django 4.2.5 on 2024-01-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0009_chatgroup_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='lead_status',
            field=models.CharField(choices=[('New Lead', 'New Lead'), ('Accept', 'Accept'), ('Active', 'Active'), ('PreEnrolled', 'PreEnrolled'), ('Enrolled', 'Enrolled'), ('Inprocess', 'Inprocess'), ('Ready To Submit', 'Ready To Submit'), ('Appointment', 'Appointment'), ('Ready To Collection', 'Ready To Collection'), ('Result', 'Result'), ('Delivery', 'Delivery'), ('Reject', 'Reject'), ('Case Initiated', 'Case Initiated')], default='New Lead', max_length=100),
        ),
    ]
