# Generated by Django 4.2.5 on 2023-12-15 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0009_alter_visacountry_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('lastupdated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('visa_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.visacountry')),
            ],
            options={
                'db_table': 'VisaCategory',
            },
        ),
    ]
