# Generated by Django 4.2.5 on 2024-01-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0010_alter_enquiry_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
