# Generated by Django 4.2.5 on 2023-12-15 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0010_visacategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visacategory',
            name='status',
        ),
    ]
