# Generated by Django 4.2.5 on 2024-01-05 05:32

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0011_alter_enquiry_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Country',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
