# Generated by Django 4.2.5 on 2023-12-15 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0012_documentcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_size', models.FloatField()),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('document_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.documentcategory')),
                ('lastupdated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
