# Generated by Django 4.2.5 on 2023-12-26 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0010_notes'),
        ('crm_app', '0012_alter_agentkyc_uploaded_on'),
    ]

    operations = [
    ]
