# Generated by Django 4.2.5 on 2023-12-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0013_merge_0010_notes_0012_alter_agentkyc_uploaded_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='adhar_card_back',
            field=models.FileField(blank=True, null=True, upload_to='media/Agent/Kyc'),
        ),
        migrations.AddField(
            model_name='agent',
            name='adhar_card_front',
            field=models.FileField(blank=True, null=True, upload_to='media/Agent/Kyc'),
        ),
        migrations.AddField(
            model_name='agent',
            name='pancard',
            field=models.FileField(blank=True, null=True, upload_to='media/Agent/Kyc'),
        ),
        migrations.AddField(
            model_name='agent',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='media/Agent/Kyc'),
        ),
    ]
