# Generated by Django 4.2.5 on 2023-12-27 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0014_agent_adhar_card_back_agent_adhar_card_front_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='mailing_country',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='mailing_phone',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='permanent_city',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='permanent_country',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='permanent_state',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='permanent_zipcode',
        ),
        migrations.CreateModel(
            name='Work_Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=244, null=True)),
                ('designation', models.CharField(blank=True, max_length=244, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=244, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('describe', models.TextField(blank=True, null=True)),
                ('enquiry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.enquiry')),
            ],
        ),
        migrations.CreateModel(
            name='TestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('PTE', 'PTE'), ('TOEFL', 'TOEFL'), ('IELTS', 'IELTS')], max_length=100)),
                ('exam_date', models.DateField()),
                ('reading', models.IntegerField()),
                ('listening', models.IntegerField()),
                ('speaking', models.IntegerField()),
                ('writing', models.IntegerField()),
                ('overall_score', models.IntegerField()),
                ('enquiry_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.enquiry')),
            ],
        ),
        migrations.CreateModel(
            name='Education_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_of_education', models.CharField(blank=True, max_length=100, null=True)),
                ('highest_level_education', models.CharField(blank=True, max_length=100, null=True)),
                ('grading_scheme', models.CharField(blank=True, max_length=100, null=True)),
                ('grade_avg', models.CharField(blank=True, max_length=100, null=True)),
                ('recent_college', models.BooleanField(blank=True, null=True)),
                ('level_education', models.CharField(blank=True, max_length=100, null=True)),
                ('country_of_institution', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_institution', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_language', models.CharField(blank=True, max_length=100, null=True)),
                ('institution_from', models.DateField(blank=True, null=True)),
                ('institution_to', models.DateField(blank=True, null=True)),
                ('degree_Awarded', models.CharField(blank=True, max_length=100, null=True)),
                ('degree_Awarded_On', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('Province', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('enquiry_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.enquiry')),
            ],
        ),
        migrations.CreateModel(
            name='Background_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_information', models.CharField(max_length=244)),
                ('enquiry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.enquiry')),
            ],
        ),
    ]
