# Generated by Django 4.2.5 on 2023-12-16 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0014_alter_document_lastupdated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCategoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_category', to='crm_app.visacategory')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm_app.visacountry')),
                ('document', models.ManyToManyField(related_name='document', to='crm_app.document')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_subcategory', to='crm_app.visacategory')),
            ],
        ),
    ]
