# Generated by Django 4.2.5 on 2023-12-26 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0014_agent_adhar_card_back_agent_adhar_card_front_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnqAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('Process', 'Process'), ('Done', 'Done')], default='Process', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.enquiry')),
            ],
            options={
                'db_table': 'Enquiry Appointment',
            },
        ),
    ]
