# Generated by Django 4.2.5 on 2023-12-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0015_enqappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enqappointment',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
