# Generated by Django 4.2.5 on 2023-12-16 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0015_casecategorydocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casecategorydocument',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='casecategorydocument',
            name='last_updated_on',
        ),
    ]
