# Generated by Django 4.2.5 on 2023-12-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0016_alter_enquiry_emergency_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background_information',
            name='background_information',
            field=models.CharField(blank=True, max_length=244, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='emergency_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('PTE', 'PTE'), ('TOEFL', 'TOEFL'), ('IELTS', 'IELTS')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='listening',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='overall_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='reading',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='speaking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='writing',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
