# Generated by Django 4.2.5 on 2023-12-16 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0016_remove_casecategorydocument_last_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casecategorydocument',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='casecategorydocument',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casecategorydocument',
            name='last_updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
