# Generated by Django 4.2.5 on 2023-12-16 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0017_remove_casecategorydocument_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=20)),
                ('branch_source', models.CharField(choices=[('COCO', 'Company Owned Company Operated'), ('COFO', 'Company Owned Franchise Operated'), ('FOCO', 'Franchise Owned Company Operated'), ('FOFO', 'Franchise Owned Franchise Operated')], max_length=50)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
