# Generated by Django 4.2.5 on 2023-12-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0019_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('zipcode', models.IntegerField()),
                ('docker_no', models.CharField(max_length=100)),
                ('sender_no', models.CharField(blank=True, max_length=15, null=True)),
                ('receiver_no', models.CharField(blank=True, max_length=15, null=True)),
                ('courier_no', models.CharField(max_length=15)),
                ('receiver_address', models.CharField(max_length=150)),
                ('sender_address', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('Pick', 'Pick'), ('In Transit', 'In Transit'), ('Receive', 'Receive')], max_length=50)),
                ('lastupdated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
