# Generated by Django 4.2.5 on 2023-12-27 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0016_alter_enqappointment_created_date'),
        ('crm_app', '0019_alter_enquiry_email_alter_enquiry_spouse_email_and_more'),
    ]

    operations = [
    ]
