# Generated by Django 5.0 on 2023-12-18 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0020_courieraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='casecategorydocument',
            name='category',
        ),
        migrations.RemoveField(
            model_name='casecategorydocument',
            name='country',
        ),
        migrations.RemoveField(
            model_name='casecategorydocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='casecategorydocument',
            name='last_updated_by',
        ),
        migrations.DeleteModel(
            name='CourierAddress',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_category',
        ),
        migrations.RemoveField(
            model_name='document',
            name='lastupdated_by',
        ),
        migrations.RemoveField(
            model_name='group',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_member',
        ),
        migrations.RemoveField(
            model_name='visacategory',
            name='visa_country_id',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='CaseCategoryDocument',
        ),
        migrations.DeleteModel(
            name='DocumentCategory',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='VisaCategory',
        ),
    ]
