# Generated by Django 5.0 on 2023-12-18 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0021_remove_branch_last_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('zipcode', models.IntegerField()),
                ('docker_no', models.CharField(max_length=100)),
                ('sender_no', models.CharField(blank=True, max_length=15, null=True)),
                ('receiver_no', models.CharField(blank=True, max_length=15, null=True)),
                ('courier_no', models.CharField(blank=True, max_length=15, null=True)),
                ('receiver_address', models.CharField(max_length=150)),
                ('sender_address', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('Pick', 'Pick'), ('In Transit', 'In Transit'), ('Receive', 'Receive')], max_length=50)),
                ('lastupdated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Document_category', models.CharField(max_length=200)),
                ('lastupdated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelTable(
            name='visacountry',
            table=None,
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=20)),
                ('branch_source', models.CharField(choices=[('COCO', 'Company Owned Company Operated'), ('COFO', 'Company Owned Franchise Operated'), ('FOCO', 'Franchise Owned Company Operated'), ('FOFO', 'Franchise Owned Franchise Operated')], max_length=50)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_size', models.FloatField()),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.documentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group_member', models.ManyToManyField(related_name='groups_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('lastupdated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('visa_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.visacountry')),
            ],
            options={
                'db_table': 'VisaCategory',
            },
        ),
        migrations.CreateModel(
            name='CaseCategoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm_app.visacountry')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ManyToManyField(related_name='document', to='crm_app.document')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_category', to='crm_app.visacategory')),
            ],
        ),
    ]
