# Generated by Django 5.0 on 2023-12-20 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0022_courieraddress_documentcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_size',
        ),
    ]
